### ISSUE TITLE
Public TODO list

### ISSUE THREAD

**Issue by EndlesslyFlowering** [EndlesslyFlowering/ReShade_HDR_shaders#10]
colour_space:
- [ ] clean up after the asfloat changes (some namespaces aren't needed anymore)

hdr_analysis:
- [ ] redo font atlas texture (only thing left is to write a script and hope it works out...)
- [ ] add assets for the histogram and CIE diagram that are half in width and height (for SteamOS)
- [ ] add auto detection for the size of all analysis elements (font, CIE diagram, histogram, etc)
- [ ] add heatmap scale for all heatmap modes (halfway? done)
- [ ] add colour space map scale
- [ ] disabling some features breaks some visualisation features (csp map doesn't work without csp percentages for example)
- [ ] bring overlay alpha "in line" with single trigger technique for HDR10 output
- [ ] improve vertex shader for clearing the brightness histogram with barebones Vertex shader?
- [ ] add namespace for UI
- [ ] add separate pixel/compute shader for combining the colour space outlines?
- [ ] rework "DISPATCH_DOESNT_OVERFLOW" (should probably be removed)
- [ ] fix CIE diagram texture offset (it displays "correct" now but it actually isn't...)
- [ ] use atomic ops for max/avg/minCLL and other compute shaders (remove dispatch overflow check in the process)
      -> AdressU/V/W = BORDER; you can't set the BORDER value (yet?) but it's float4(0,0,0,0) by default (<https://github.com/crosire/reshade/blob/5c8b8f0993a46fcd2f471181b002fb7f549c33c5/source/runtime.cpp#L2371-L2374>)
      -> 64 threads
- [ ] use direct conversion from source csp (scRGB or HDR10) to test csp for colour space detection instead of converting to XYZ first and then to the test csp

filmgrain:
- [ ] use "asfloat" for all float variables
- [ ] implement vertex shader for optimisation
- [ ] add namespace for UI

hdr_black_floor_fix:
- [ ] add chroma adjustment from BT.2390 too? maybe as option only (I think I already tried this and it caused issues)
- [ ] use BT.709<->LMS matrices instead of BT.2020<->LMS matrices if possible (needs performance testing)

scrgb_trc_fix:
- [ ] add namespace for UI

inverse_tone_mapping:
- [ ] implement vertex shader for optimisation
- [ ] general clean up needed
- [ ] finish BT.2446 Method C
- [ ] LUT based inverse tone mapping (this includes implementing it for BT.2390; also needs a way to do perceptual scaling)

tone_mapping:
- [ ] add black point adaption for every tone mapper
- [ ] do maxCLL calc in quarter res? and with atomic ops
- [ ] put excessive checks for setup of the tone mappers into vertex shader?
- [ ] add option to do BT.2446A as post adjustment of BT.2390/Dice
- [ ] use BT.709 RGB->LMS matrix instead of rotating into BT.2020? (needs performance testing)
- [ ] make Dice use the same knee function as BT.2390?
- [ ] put oneMinusKneeStart into the vertex shader?
- [ ] LUT based tone mapping (look into perceptual scaling in LUTs)

**Comment by ABDX80** [comment]
Are we still getting some Test Patterns to fine tune the shaders?

P.S. Phenomenal Mod.

**Comment by EndlesslyFlowering** [comment]
> P.S. Phenomenal Mod.

thanks! :)

> Are we still getting some Test Patterns to fine tune the shaders?

not sure what you mean exactly?

**Comment by ABDX80** [comment]
The 'Test Patterns' you mentioned on "Plasma TV for Gaming" YT channel.
Test Patterns that we could use in-game to fine tune HDR properly. For black levels, highlights etc...
@EndlesslyFlowering

**Comment by EndlesslyFlowering** [comment]
> The 'Test Patterns' you mentioned on "Plasma TV for Gaming" YT channel. Test Patterns that we could use in-game to fine tune HDR properly. For black levels, highlights etc... @EndlesslyFlowering

Ah that.
After I finish all the Steam Deck related stuff I can expose it (it's basically done :) )

**Comment by ABDX80** [comment]
Hello again!
Could you please add the functionality so that the HDR Analysis tool works for Windows 11 AutoHDR.
This'll help a lot. Since AutoHDR even have raised black levels.

**Comment by EndlesslyFlowering** [comment]
> Hello again! Could you please add the functionality so that the HDR Analysis tool works for Windows 11 AutoHDR. This'll help a lot. Since AutoHDR even have raised black levels. @EndlesslyFlowering

Impossible.

**Comment by dakerano66** [comment]
@EndlesslyFlowering I would like to know what is SDR TRC fix. Something would be wrong if I use it on HDR?

I am using it on HDR because seems to fix the black floor automatically

Also, what is input lower gamma? If I enable my tv's black frame insertion which dimms the picture I could increase this value to get as bright as it was without bfi. Doing so, the perfect black does not change, the color clipping and white clipping seems correct, but I am unsure if it is washing out the picture or crashing midtones, I dont know which test patern should I use as reference to check for that. HDR analisis tool cant be used as reference, because the spectrum does not change when enabling BFI altought the picture is obvioulsy darker (means blacks and midtones spectrum should be lower, but it is not reflected)

Thank you for your work.

**Comment by EndlesslyFlowering** [comment]
> @EndlesslyFlowering I would like to know what is SDR TRC fix. Something would be wrong if I use it on HDR?
> 
> I am using it on HDR because seems to fix the black floor automatically

it's in the naming: SDR only

> Also, what is input lower gamma?

I assume you mean "input power gamma":
you can choose between sRGB and power gamma, sRGB is not really a gamma but it simplifies usage of the terms. 2.2, 2.4 or 2.6 are all "power gammas" as in x to the power of 2.2 or 2.4 (x^2.2).

> If I enable my tv's black frame insertion which dimms the picture I could increase this value to get as bright as it was without bfi. Doing so, the perfect black does not change, the color clipping and white clipping seems correct, but I am unsure if it is washing out the picture or crashing midtones, or something. I dont know which test patern should I use as reference to check for that. HDR analisis tool cant be used as reference, because the spectrum does not change when enabling BFI altought the picture is obvioulsy darker (means blacks and midtones spectrum should be lower, but it is not reflected)

I guess you are looking for gamma adjustment of the lower range?
I am planning on creating such a shader in the future (no estimates).
SDR TRC is definitely the wrong one for this.

**Comment by aron7awol** [comment]
I see "add back RGB values from cursor" marked as completed on the hdr_and_sdr_analysis list, but as far as I can tell this functionality to show the RGB values of the cursor does not currently exist?

**Comment by EndlesslyFlowering** [comment]
> I see "add back RGB values from cursor" marked as completed on the hdr_and_sdr_analysis list, but as far as I can tell this functionality to show the RGB values of the cursor does not currently exist? Did it exist in an older version?

when something is marked as completed here, it's pushed to the github master. which does not mean that there is a release yet.

in this case there is a pre-release

**Comment by ABDX80** [comment]
### **Greetings,**

Is the _'roll off stopping point'_ in black floor lowering shader's functionality altered?
In earlier versions, the default value was '10.0nits' I'd loved using it on 1.0nit. It would work brilliantly.
But now with newer version of this shader, if I choose 1.0 or 10.0nits the screen goes completely dark?
I have to now use either 1000.0nits or 10000.0nits why is that?

A brief explanation will help a lot on how to use it properly.

**Thanks!**
@EndlesslyFlowering
